print('Hello World')
print('What is your name?')
name = input()
print('Hi ' + name + ', it is nice to meet you!')
print('Your name is ' + str(len(name)) + ' characters long')
print('How old are you?')
age = input()
print('So you are ' + age + ' old! You will turn ' + str(int(age)+1) + ' next year')